language: python
python: 2.7
sudo: false
cache:
  directories:
  - buildout-cache
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
matrix:
  fast_finish: true
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - if test "$PLONE_VERSION" = "4.2"; then echo >> travis.cfg; echo "Products.membrane = 2.1.13" >> travis.cfg; fi
  - mkdir -p buildout-cache/downloads
  - pip install zc.buildout
  - buildout -c travis.cfg annotate
  - buildout -c travis.cfg -N -q -t 3
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/test
